apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-tunnel-deployment
  labels:
    app: udp-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-tunnel
  template:
    metadata:
      labels:
        app: udp-tunnel
    spec:
      imagePullSecrets:
        - name: ghcr-credentials #  create secret before apply
      containers:
        - name: udp-tunnel-container
          image: ghcr.io/achilleas2942/cnmpc-udp-tunnel:latest
          resources:
          command: ["/bin/bash", "-c", "./root/catkin_ws/src/cnmpc_udp_tunnel/src/run_tunnel.sh"]
          env:
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ROS_MASTER_URI
              value: "http://roscore:11311"
