apiVersion: v1
kind: Service
metadata:
  name: port0
spec:
  type: NodePort
  selector:
    app: udp-tunnel
  ports:
    - protocol: UDP
      port: 30100
      targetPort: 30100
      nodePort: 30100
