apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner-deployment
  labels:
    app: planner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planner
  template:
    metadata:
      labels:
        app: planner
    spec:
      imagePullSecrets:
        - name: ghcr-credentials #  create secret before apply
      containers:
        - name: planner-container
          image: ghcr.io/achilleas2942/cnmpc-planner:latest
          resources:
          command: ["/bin/bash", "-c", "./root/catkin_ws/src/cnmpc_planner/src/run_planner.sh"]
          env:
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ROS_MASTER_URI
              value: "http://roscore:11311/"
